version: 2
jobs:
  qa:
    working_directory: ~/costlocker/reports
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_RESULTS: /tmp/circleci-test-results
    docker:
    - image: zdenekdrahos/phpqa:v1.21.1
    steps:
    - checkout

    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_RESULTS
    - run: composer install --no-interaction --ignore-platform-reqs

    - run: bin/qa
    - run: cp ./var/QA/log-junit.xml $CIRCLE_TEST_RESULTS
    - run: cp -r ./var/QA $CIRCLE_ARTIFACTS

    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts

  docker:
    working_directory: ~/costlocker/reports
    parallelism: 1
    docker:
    - image: docker:17.05.0-ce-git
    steps:
    - checkout
    - setup_remote_docker
    - run: .circleci/build-docker-image

workflows:
  version: 2
  build:
    jobs:
      - qa
      - docker:
          requires:
            - qa
