version: 2
jobs:
  qa:
    working_directory: ~/costlocker/reports
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_RESULTS: /tmp/circleci-test-results
    docker:
    - image: zdenekdrahos/phpqa:v1.21.1
    steps:
    - checkout

    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_RESULTS
    - run: composer install --no-interaction --ignore-platform-reqs

    - run: bin/qa
    - run: cp ./var/QA/log-junit.xml $CIRCLE_TEST_RESULTS
    - run: cp -r ./var/QA $CIRCLE_ARTIFACTS

    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts

  docker:
    working_directory: ~/costlocker/reports
    parallelism: 1
    docker:
    - image: docker:17.05.0-ce-git
    steps:
    - checkout
    - setup_remote_docker
    # TODO: use Github Docker Registry when it's public or beta inviation is accepted
    # 1) Create token for pushing docker image (https://help.github.com/en/articles/configuring-docker-for-use-with-github-package-registry)
    # 2) Add DOCKER_USER, DOCKER_TOKEN env vars (https://circleci.com/gh/costlocker/reports/edit#env-vars)
    # 3) Check that build works and docker image is published (https://circleci.com/gh/costlocker/reports/29)
    #    $ docker run --rm -it docker.pkg.github.com/costlocker/reports/master:commit bin/console report --help
    # 4) Update Docker help in README.md
    - run: .circleci/build-docker-image || echo "Skipped publish (Github Docker Registry not available)"

workflows:
  version: 2
  build:
    jobs:
      - qa
      - docker:
          requires:
            - qa
